# Generated by Django 5.0.13 on 2025-03-24 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='Users',
        ),
    ]
